### ISSUE TITLE
How to use buy_limit without limit price

### ISSUE THREAD

**Issue by tuloski** [askmike/bitstamp#32]
Hello, I see in the following code:
```
Bitstamp.prototype.buy = function(market, amount, price, limit_price, callback) {
  this._post(market, 'buy', callback, {
    amount: amount,
    price: price,
    limit_price: limit_price
  });
}
```
that the buy (and sell) API calls have a limit_price field, which is optional. I'm a little noob on js, but how can I do a buy order without putting the "limit_price" arg?
Can I just do "privateBitstamp.buy('btcusd', amount, price, console.log);"? Will the limit_price not be used in that case?

**Comment by askmike** [comment]
You can pass undefined undefined, which will strip out the `limit_price` and not send it at all (that stripping happens [here](https://github.com/askmike/bitstamp/blob/master/bitstamp.js#L8-L14))
