### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by tuxitor** [askmike/bitstamp#36]
When doing a call to a nonexisting endpoint, this one caoncats the error code and buffer. which means I am getting the entire html page in return.

```javascript
      if (res.statusCode !== 200) {
        return callback(new Error('Bitstamp error ' + res.statusCode + ': ' + buffer));
      }
```

Is it possible get the return as two different entities, preferably as an object with statusCode and a short descriptive text like this for the most common error codes? 
```
{ statusCode: 404, statusText: 'Not found' }
```
At least separate the statusCode from the buffer.

**Comment by tuxitor** [comment]
@askmike 
A reminder

**Comment by askmike** [comment]
Sorry that it took so long for a fix :(

**Comment by askmike** [comment]
You can now access a `meta` property on the error that (if bitstamp returned valid JSON) contains that object.
