### ISSUE TITLE
nonce error!?

### ISSUE THREAD

**Issue by TestniTester** [askmike/bitstamp#39]
hi,
when i call
privateBitstamp.buy
i get error invalid nonce?
any idea?
BUT
if i call
privateBitstamp.balanc
i get the balance

my bad... generated new keys... now works perfectly!

**Comment by askmike** [comment]
Hey,

Do you get that every time you do the call? Are you using the API key for anything else as well?

**Comment by askmike** [comment]
Assuming the above!
