### ISSUE TITLE
help on withdrawl of XRP?

### ISSUE THREAD

**Issue by TestniTester** [askmike/bitstamp#42]
hi,
i just discovered your bitstamp node
and im looking in documentation for withdrawing BTC and XRP
now for XRP in dont get this from documentation:
privateBitstamp.ripple_withdrawal(amount, address, currency);
now my questions:
1. XRP needs also a destination tag !? where can i add it?
2. what is currency ?
Thank you!

**Comment by TestniTester** [comment]
i guess not supported by bitstamp?

**Comment by krystianity** [comment]
@TestniTester it is supported by bitstamp, checkout https://github.com/krystianity/node-bitstamp

**Comment by askmike** [comment]
Hey! I just added this, you can call the new method like so:

    bitstamp.xrp_withdrawal(amount, address, destination_tag, callback);
