### ISSUE TITLE
[enhancement] Make async requests

### ISSUE THREAD

**Issue by tuloski** [askmike/bitstamp#47]
Hi,
would it be possible to make all the request async, possibly with promises?

**Comment by KevinJue** [comment]
@tuloski you got the solution here https://github.com/krystianity/node-bitstamp

**Comment by askmike** [comment]
@tuloski it follows default node callback style. You can use a tool like [pify](https://www.npmjs.com/package/pify) to easily turn this into a promise.

@KevinJue that's a completely different project.
